version: '3.8'

services:
  # Nginx - ДОЛЖЕН БЫТЬ ПЕРВЫМ для проксирования
 nginx:
  image: nginx:alpine
  command: ["nginx","-g","daemon off;"]
  expose: ["80"]           # ← добавили
  volumes:
    - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    - frontend_build:/usr/share/nginx/html:ro
  depends_on: [backend]
  restart: always

  # Backend API
  backend:
    build: ./backend
    expose: ["8000"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_IDS=${ADMIN_IDS}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - TIMEZONE_OFFSET=${TIMEZONE_OFFSET}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ENVIRONMENT=${ENVIRONMENT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
    
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]