version: '1'
services:
  - name: raffle-api
    type: web
    build:
      context: ./backend
      dockerfile: Dockerfile
    env:
      DATABASE_URL: ${DATABASE_URL}
      BOT_TOKEN: ${BOT_TOKEN}
      WEBAPP_URL: ${WEBAPP_URL}
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_IDS: ${ADMIN_IDS}
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      TIMEZONE_OFFSET: ${TIMEZONE_OFFSET}
      CORS_ORIGINS: ${CORS_ORIGINS}
      ENVIRONMENT: ${ENVIRONMENT}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}

  - name: raffle-app
    type: web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_WS_URL: ${REACT_APP_WS_URL}
      REACT_APP_TELEGRAM_BOT_USERNAME: ${REACT_APP_TELEGRAM_BOT_USERNAME}

  - name: raffle-bot
    type: worker
    build:
      context: ./bot
      dockerfile: Dockerfile
    env:
      BOT_TOKEN: ${BOT_TOKEN}
      WEBAPP_URL: ${WEBAPP_URL}
      API_URL: ${API_URL}
      ADMIN_IDS: ${ADMIN_IDS}